[package]
name = "testing"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "testing"
path = "testing.rs"

[workspace]
members = ["calc", "mechanic", "api", "mlua", "async"]

[dependencies]
expect-test = "1.4.0"
